# numpy

## importing numpy as its common alias

In [1]:
import numpy as np

## Basics of numpy array

In [2]:
arr = np.array(['a', 'bb', 'ccc'])
print(arr)

['a' 'bb' 'ccc']


In [3]:
##multidimensional array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#dimension of array
arr2.ndim

2

In [5]:
arr2.shape

(3, 3)

In [6]:
arr2.dtype

dtype('int32')

In [7]:
#4 bcoz int32 is equal to 4 bytes
arr2.itemsize

4

In [8]:
#numer of elements in array
arr2.size

9

In [9]:
#multiply the sizeofaelements with total no of elements
arr2.nbytes

36

## manipulating arrays

In [10]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#to access element 8
print(arr2[2][1])
print(arr2[2,1])

8
8


In [12]:
##accessing a whole row and whole column
print("2nd row ", arr2[1,:])
print("3rd column ", arr2[:,2])

2nd row  [4 5 6]
3rd column  [3 6 9]


In [13]:
#multidimensional array 
arr3 = np.array([[[2,3],[4,5]],[[6,5],[9,0]]])
print(arr3)

[[[2 3]
  [4 5]]

 [[6 5]
  [9 0]]]


In [14]:
#updating the value of 6 to 7
arr3[1,0,0] = 7
print(arr3)

[[[2 3]
  [4 5]]

 [[7 5]
  [9 0]]]


## Initializing different type of Arrays

In [15]:
#array with all entries as 0
arr4 = np.zeros(4, dtype ='int')
arr5 = np.zeros((3,2))
print(arr4)
print(arr5)

[0 0 0 0]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
#array with all entries as 1
arr6 = np.ones(4)
arr7 = np.ones((3,2), dtype ='int')
print(arr4)
print(arr5)

[0 0 0 0]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
#array with all entries of your choice
print(np.full((4,5),76))

[[76 76 76 76 76]
 [76 76 76 76 76]
 [76 76 76 76 76]
 [76 76 76 76 76]]


In [18]:
#array of random numbers
print(np.random.rand(2,4))
#array of random int numbers with range(-10,10)
print(np.random.randint(-10, 15, size=(2,4)))

[[0.81825637 0.05019147 0.76610524 0.9555047 ]
 [0.76606056 0.98276128 0.5914281  0.61581734]]
[[ 3  8 -4 -8]
 [-3  2 -9 -9]]


In [19]:
#n identity matrix
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [20]:
arr9 = np.array([[1,2,3]])
np.repeat(arr9,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [21]:
#shortcut to initialize a array of your choice
arr10 = np.ones((5,5))
arr11 = np.full((3,3),2)
arr11[1,1]=3
print(arr10)
print(arr11)
arr10[1:4,1:4]=arr11
print(arr10)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2 2]
 [2 3 2]
 [2 2 2]]
[[1. 1. 1. 1. 1.]
 [1. 2. 2. 2. 1.]
 [1. 2. 3. 2. 1.]
 [1. 2. 2. 2. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
#copy the contents of a arrray to another array
arr12 = arr11.copy()
print(arr12)

[[2 2 2]
 [2 3 2]
 [2 2 2]]


## Performing basic math operations

In [23]:
print(arr12)
print(arr12+2)

[[2 2 2]
 [2 3 2]
 [2 2 2]]
[[4 4 4]
 [4 5 4]
 [4 4 4]]


In [24]:
print(arr12**2)

[[4 4 4]
 [4 9 4]
 [4 4 4]]


In [25]:
arr13 = np.array([0,30,45,60,90])

In [26]:
# output in radians
print(np.sin(arr13))
print(np.cos(arr13))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [27]:
# output in degrees
print(np.sin(arr13*np.pi/180))
print(np.cos(arr13*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


## Linear Algebra

In [28]:
print(arr2)
print(arr11)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 3 2]
 [2 2 2]]


In [29]:
# matrix multiplication
np.matmul(arr2, arr11)

array([[12, 14, 12],
       [30, 35, 30],
       [48, 56, 48]])

In [30]:
# matrix det
np.linalg.det(arr2)

0.0

In [31]:
# inverse of a matrix
np.linalg.inv(np.array([[1,5,3],[2,7,4],[8,1,6]]))

array([[-1.58333333,  1.125     ,  0.04166667],
       [-0.83333333,  0.75      , -0.08333333],
       [ 2.25      , -1.625     ,  0.125     ]])

## Statistics

In [32]:
stat = np.array([22,14,9,43,13,95,54,88])

In [33]:
## min, max, mean, median, sum
print(np.sum(stat))
print(np.min(stat))
print(np.max(stat))
print(np.mean(stat))
print(np.median(stat))

338
9
95
42.25
32.5


In [34]:
##changing shape of array
print(arr12)
print(arr12.reshape(1,9))

[[2 2 2]
 [2 3 2]
 [2 2 2]]
[[2 2 2 2 3 2 2 2 2]]


In [35]:
#vertically stacking two arrays
print(arr2)
print(arr11)
print(np.vstack([arr2,arr11]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 3 2]
 [2 2 2]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 2 2]
 [2 3 2]
 [2 2 2]]


In [36]:
#horizontal stacking two arrays
print(np.hstack((arr2,arr11)))

[[1 2 3 2 2 2]
 [4 5 6 2 3 2]
 [7 8 9 2 2 2]]


In [37]:
arr14 = np.random.randint(0,100, size=(1,100))
print(arr14)

[[16 78 78  5 20 13 16 37 90 75 78  0 20 50  8 22 65 59 42 26 90 40 29 84
   1 33 91 92  1 27 94 96 49 20 34 78 28 96 10 59  0 20 82 95 46 26 63 67
  96 77 56 37 80 85 43 98 40 81 82 67 23 64 75 46 84 79 77 51 98 32 56 83
  87 95 62 21 21 35  8 53 31 79 17 64 30 89 89 41  9 94 49 85  8 55 80 86
  41 69 79  9]]


In [38]:
# sort array
np.sort(arr14)

array([[ 0,  0,  1,  1,  5,  8,  8,  8,  9,  9, 10, 13, 16, 16, 17, 20,
        20, 20, 20, 21, 21, 22, 23, 26, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 37, 37, 40, 40, 41, 41, 42, 43, 46, 46, 49, 49, 50, 51,
        53, 55, 56, 56, 59, 59, 62, 63, 64, 64, 65, 67, 67, 69, 75, 75,
        77, 77, 78, 78, 78, 78, 79, 79, 79, 80, 80, 81, 82, 82, 83, 84,
        84, 85, 85, 86, 87, 89, 89, 90, 90, 91, 92, 94, 94, 95, 95, 96,
        96, 96, 98, 98]])

In [39]:
# filtering array
print((arr14>50) & (arr14<75))

[[False False False False False False False False False False False False
  False False False False  True  True False False False False False False
  False False False False False False False False False False False False
  False False False  True False False False False False False  True  True
  False False  True False False False False False False False False  True
  False  True False False False False False  True False False  True False
  False False  True False False False False  True False False False  True
  False False False False False False False False False  True False False
  False  True False False]]


In [40]:
# comparison
print(arr2)
print(arr11)
print(np.array_equal(arr2,arr11))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 3 2]
 [2 2 2]]
False
